version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
      python: 3.7
    commands:
      - pip install --upgrade 'six==1.15.0'
      - pip install --upgrade 'pyyaml~=5.1'
      - pip install --upgrade 'boto3==1.19.5'
      - pip install pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      # run pre-commit on all files in repo
      - pre-commit run --all-files
      # run through the build lifecycle for the notification channel resource provider
      - cd "$CODEBUILD_SRC_DIR/aws-fms-notificationchannel"
      - mvn clean verify --no-transfer-progress
      # run through the build lifecycle for the policy resource provider
      - cd "$CODEBUILD_SRC_DIR/aws-fms-policy"
      - mvn clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-fms-notificationchannel/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-fms-policy/rpdk.log"
